* first steps

mkdir mysite and cd into it

virtualenv .

(total size is like 16 mb)

list the files, there is a bin folder in addition to others

source bin/activate

pip install django

(now total size is just shy of 60mb)

python -m django --version

which python

django-admin startproject mysite

cd mysite

which python

source ./bin/activate

python manage.py runserver

(access on browser (localhost:8000))

#create an app

mkdir polls && cd polls

edit views.py (make modifications as given in tutorial)

edit the polls/urls.py file (make modifications as given in tutorial)

edit the mysite/urls.py file (make modifications as given in tutorial)



* what do i need to install?
sudo apt-get install python3
sudo apt-get install pip


The proper way of installing python so that it does not touch root

simply run

virtualenv -p python3 envname


** what is this env or virtual env or virtual environment?
* how to find documentation?
** online documentation
** offline documentation 
*** the python interpreter
import os
help()
help(os)
# use python interpreter within the virtualenv
import django
dir(django)
help(django)
*** pydoc in the browser
man pydoc
pydoc -w os
you find os.html
open os.html in browser

pydoc -p 4000
in your browser you can access the page
localhost:4000

* understanding some big picture concepts
** what is model view controller (mpv)?
** how does this mpv compare with design patterns that i kind of heard/learned in java?
* trash

